### ISSUE TITLE
Block Embed Icon doesn't work on editor configuration page

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/ckeditor_blocks#12]
When you go to configure CKEditor for this module, the icon does not display as I would expect on that configuration page:

![image](https://user-images.githubusercontent.com/3144571/153996535-defc5b39-a0ed-418c-8a6a-e6ed1c15ff34.png)

This is what we see in the actual CKEditor configuration window.

![image](https://user-images.githubusercontent.com/3144571/153996692-635c4c57-2c9e-4923-855d-ad9919943cf0.png)

**Comment by juanolalla** [comment]
Pull request fixing this: https://github.com/backdrop-contrib/ckeditor_blocks/pull/31
