### ISSUE TITLE
FUTURE: Dashboard Blocks

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/ckeditor_blocks#15]
In my initial testing, most of the Dashboard blocks were not working and since we don't really envision a large use case for Dashboard blocks in the body field of other nodes or blocks, we've decided to ignore them for now.

Let us know if you would like this module to support Dashboard blocks.

**Comment by jenlampton** [comment]
This should be solved by https://github.com/backdrop-contrib/ckeditor_blocks/issues/22, when we disallow all dashboard bocks. (If there is a use-case for dashboard blocks, we can re-evaluate. Please re-open this issue, or create a new one).
