### ISSUE TITLE
FUTURE: Decide how to handle new blocks provided by contrib

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/ckeditor_blocks#16]
We need to think about how this module handles new blocks provided by contrib modules that might work very well with the module.

**Comment by jenlampton** [comment]
This should be solved by https://github.com/backdrop-contrib/ckeditor_blocks/issues/22. 

If someone wants to embed a contrib block type, they can open an issue, we can test that block type, and if it works, or can be made to work with a reasonable amount of effort, then we can add that block type as supported/allowed :)
