### ISSUE TITLE
Notices after saving ckeditor content with a block inserted

### ISSUE THREAD

**Issue by mikesoltis** [backdrop-contrib/ckeditor_blocks#19]
![notices](https://user-images.githubusercontent.com/78069725/154187875-26d1559e-9110-4a53-a8d1-1e0fe959f1a8.png)

**Comment by stpaultim** [comment]
I've been seeing many of these message in the log, but did not get an error notification like this. 

Anyway, I'm hopeful that cleaning up these messages will be easier the the work that went into this module so far. We'll be trying to work on these tonight.

**Comment by stpaultim** [comment]
@mikesoltis I'm pretty sure that you will find all of the errors fixed in the current dev version of the module. If you have time to test again, it would be appreciated.

**Comment by stpaultim** [comment]
I've done quite a bit of testing and am pretty confident that this is fixed. Please, reopen if you notice this again.
