### ISSUE TITLE
Block does not display

### ISSUE THREAD

**Issue by mikesoltis** [backdrop-contrib/ckeditor_blocks#20]
I entered text into ckeditor and then added a block (fig 1).  When I save the content, the text is displayed but the block does not display (fig 2).

fig 1
![text_block_in_ckeditor](https://user-images.githubusercontent.com/78069725/154188078-c7a5f40b-1f72-42f7-873b-8a0d18dbb2d5.png)

fig2
![text_block_saved](https://user-images.githubusercontent.com/78069725/154188694-e486cad2-249b-4ad3-99f9-ab1b35aa5edc.png)

**Comment by stpaultim** [comment]
@mikesoltis Here are the proper steps to configure the module. Did you do these?

1) Enable the module
2) Edit the "filtered html" text filter here - admin/config/content/formats/filtered_html (or whichever filter you are using). Move the {Insert Block} token from "available buttons" to "active toolbar."

![image](https://user-images.githubusercontent.com/3144571/154240921-e787237a-175a-4bb0-b221-1d16f0d05af6.png)

Enable the "Backdrop Blocks" filter and make sure that it comes AFTER the Limit allowed HTML Tags filter (not sure how important this is yet, but it might solve some problems). Then save changes to the text filter.

![image](https://user-images.githubusercontent.com/3144571/154241639-80863a82-af83-4e5a-a978-e6f54c6ec786.png)


3) Now use CKEditor on a node and try adding a block. 

If things are working properly, you will see this icon in CKEditor toolbar. 

![image](https://user-images.githubusercontent.com/3144571/154241945-b7d74339-460b-4898-8381-44863d2ef837.png)

**Comment by mikesoltis** [comment]
Using the first test version: 

Following Steps:

1. Yes - module enabled
2. Yes - tken added to toolbar, however, I had not enabled the backdrop blocks filter.

It is now enabled.

3. Yes - icon displayed

The block now displays correctly!

**Comment by stpaultim** [comment]
@mikesoltis Excellent
