### ISSUE TITLE
Do not render views blocks in editor. 

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/ckeditor_blocks#27]
A views table blocks looks like a table when in edit mode, but a views grid block does not. 

Can we fix this?

**Comment by jenlampton** [comment]
The problem with rendering blocks in edit mode, is that all the styles from the front-end are not available in the editor, so you'll never get a WYSIWYG experience (which is one of the reasons why we call it a "Rich Text editor" in Backdrop). 

You've reported this problem happening with a grid block, but imagine how much worse it would be with an accordion or slideshow. 

It might be safer not to render the block at all in edit mode, but instead render some specific markup that indicates a block has been embedded in that location. It could render the same way the block does in the admin interface for layouts: show the block title + description. We could then style those identically for all blocks, creating a more consistent experience in the editor.

**Comment by juanolalla** [comment]
Consistent editor block rendering implemented in pull request: https://github.com/backdrop-contrib/ckeditor_blocks/pull/32
