### ISSUE TITLE
Add jenlampton as maintainer in README

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/ckeditor_blocks#36]
@stpaultim I believe we had discussed adding me as a maintainer either verbally, or via Zulip, but I am shocked to see that there is not an issue and an official change here in the queue -- I am so sorry if I have overstepped. I have been merging PRs assuming I was already a maintainer for this project. 

I think we are ready for an official 1.x-1.0.0 release, but I don't want to create one unless I am sure I am a maintainer :D 
PR forthcoming.

**Comment by stpaultim** [comment]
@jenlampton - No, you are exactly correct. I was a bit shocked to see that this hadn't happened yet. But, I certainly understood you to be a co-maintainer - no problems.
