### ISSUE TITLE
Clean Up Messy Code

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/ckeditor_blocks#9]
We just merged some sloppy code, because we were in a rush to test some things out and this module is NOT ready for use yet. We plan to fix that ASAP. 

This ticket is just a reminder that we'll be cleaning up the code soon. We've talked to @klonos about giving us a code review when we're done. Thanks.

**Comment by stpaultim** [comment]
We've cleaned up a bunch of the code. But, we made need to do a little more work later when we're done with features.

**Comment by jenlampton** [comment]
I'm going to close this issue in favor of more specific cleanup tasks :)
